name: fcc-bluecollar-v6

services:
  agent_worker:
    build: .
    shm_size: '2gb'
    env_file:
      - .env
    volumes:
      - shared_data:/shared
    deploy:
      replicas: 1
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: fcc-loadbalancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - agent_worker
    restart: unless-stopped

volumes:
  shared_data: