events { worker_connections 1024; }
http {
    upstream backend_agents {
        server agent_worker:8001;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://backend_agents;
            proxy_read_timeout 600s;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}