name: fcc-bluecollar-stack-V3  # <--- Hier definierst du den Projektnamen
services:
  agent_worker:
    # Wir nutzen das bereits lokal gebautes Image!
    image: fcc-agent-bluecollar:3.0
    pull_policy: never  # Erzwingt die Nutzung des lokalen Images


    shm_size: '1gb' 
    environment:
      - HEADLESS=true
      - API_HOST=0.0.0.0
      - API_PORT=8001
    deploy:
      mode: replicated
      replicas: 10  # n parallele Agenten
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80" # Nginx lauscht auf Port 8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - agent_worker
    restart: unless-stopped