events {
    worker_connections 1024;
}

http {
    upstream backend_agents {
        # Docker löst 'agent_worker' automatisch in die IPs der Replicas auf
        server agent_worker:8001;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_agents;
            
            # Lange Timeouts, da die FCC-Abfragen Zeit benötigen
            proxy_read_timeout 600s;
            proxy_connect_timeout 600s;
            proxy_send_timeout 600s;
            
            # Wichtige Header für das Weiterleiten der korrekten Ursprungsdaten
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}