name: fcc-bluecollar-puppeteer

services:
  bluecollar-agent:
    build: .
    image: bluecollar-agent-puppeteer:5.0
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - HEADLESS=false
      - API_PORT=8001
      - TZ=Europe/Berlin
      - MAX_CONCURRENT_JOBS=1 # <--- Anzaahl paralleler Jobs
    deploy:
      resources:
        limits:
          memory: 3.5G
    shm_size: '2gb'
    volumes:
      - puppeteer_tmp:/tmp

volumes:
  puppeteer_tmp: